import { Product, CommunityReport } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prismatic-evolutions-etb",
    name: "Prismatic Evolutions Elite Trainer Box",
    image: "/products/placeholder.png",
    category: "Elite Trainer Box",
    retailers: [
      {
        retailer: "walmart",
        url: "https://www.walmart.ca/search?q=prismatic+evolutions+elite+trainer+box",
        price: 74.97,
        status: "out_of_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: "2026-05-08T14:30:00Z",
      },
      {
        retailer: "pokemoncenter",
        url: "https://www.pokemoncenter.com",
        price: 69.99,
        status: "out_of_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: null,
      },
      {
        retailer: "ebgames",
        url: "https://www.ebgames.ca",
        price: 69.99,
        status: "out_of_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: "2026-05-06T11:00:00Z",
      },
    ],
  },
  {
    id: "prismatic-evolutions-bbb",
    name: "Prismatic Evolutions Binder Collection",
    image: "/products/placeholder.png",
    category: "Collection Box",
    retailers: [
      {
        retailer: "walmart",
        url: "https://www.walmart.ca",
        price: 54.97,
        status: "in_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: new Date().toISOString(),
      },
      {
        retailer: "bestbuy",
        url: "https://www.bestbuy.ca",
        price: 54.99,
        status: "out_of_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: "2026-05-09T11:00:00Z",
      },
    ],
  },
  {
    id: "surging-sparks-bb",
    name: "Surging Sparks Booster Box",
    image: "/products/placeholder.png",
    category: "Booster Box",
    retailers: [
      {
        retailer: "pokemoncenter",
        url: "https://www.pokemoncenter.com",
        price: 194.99,
        status: "in_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: new Date().toISOString(),
      },
      {
        retailer: "fourohone",
        url: "https://store.401games.ca",
        price: 179.99,
        status: "in_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: new Date().toISOString(),
      },
      {
        retailer: "bestbuy",
        url: "https://www.bestbuy.ca",
        price: 194.99,
        status: "preorder",
        lastChecked: new Date().toISOString(),
        lastInStock: null,
      },
    ],
  },
  {
    id: "destined-rivals-etb",
    name: "Destined Rivals Elite Trainer Box",
    image: "/products/placeholder.png",
    category: "Elite Trainer Box",
    retailers: [
      {
        retailer: "walmart",
        url: "https://www.walmart.ca",
        price: 59.97,
        status: "in_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: new Date().toISOString(),
      },
      {
        retailer: "bestbuy",
        url: "https://www.bestbuy.ca",
        price: 59.99,
        status: "in_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: new Date().toISOString(),
      },
      {
        retailer: "toysrus",
        url: "https://www.toysrus.ca",
        price: 59.99,
        status: "out_of_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: "2026-05-10T08:00:00Z",
      },
    ],
  },
  {
    id: "journey-together-bb",
    name: "Journey Together Booster Box",
    image: "/products/placeholder.png",
    category: "Booster Box",
    retailers: [
      {
        retailer: "pokemoncenter",
        url: "https://www.pokemoncenter.com",
        price: 194.99,
        status: "preorder",
        lastChecked: new Date().toISOString(),
        lastInStock: null,
      },
      {
        retailer: "fourohone",
        url: "https://store.401games.ca",
        price: 184.99,
        status: "preorder",
        lastChecked: new Date().toISOString(),
        lastInStock: null,
      },
      {
        retailer: "ebgames",
        url: "https://www.ebgames.ca",
        price: 194.99,
        status: "preorder",
        lastChecked: new Date().toISOString(),
        lastInStock: null,
      },
    ],
  },
];

export const MOCK_REPORTS: CommunityReport[] = [
  {
    id: "r1",
    productName: "Prismatic Evolutions Elite Trainer Box",
    retailer: "walmart",
    location: "Walmart - Mississauga (Dundas & Hurontario)",
    postalCode: "L5B 1H7",
    status: "in_stock",
    note: "Found 3 on the shelf by electronics. Vendor was just there restocking.",
    reportedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    upvotes: 24,
  },
  {
    id: "r2",
    productName: "Prismatic Evolutions Binder Collection",
    retailer: "toysrus",
    location: "Toys R Us - Scarborough Town Centre",
    postalCode: "M1P 4P5",
    status: "in_stock",
    note: "Just restocked the whole Pokemon section. Binders, tins, and blisters.",
    reportedAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    upvotes: 18,
  },
  {
    id: "r3",
    productName: "Surging Sparks Booster Box",
    retailer: "fourohone",
    location: "401 Games - Yonge St, Toronto",
    postalCode: "M4Y 1X5",
    status: "in_stock",
    note: "They have booster boxes behind the counter. Fair prices, no scalper markup.",
    reportedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    upvotes: 9,
  },
  {
    id: "r4",
    productName: "Destined Rivals Elite Trainer Box",
    retailer: "bestbuy",
    location: "Best Buy - Heartland Town Centre, Mississauga",
    postalCode: "L5R 3W3",
    status: "in_stock",
    note: "Full shelf reset in the gaming aisle. ETBs and tins all stocked up.",
    reportedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    upvotes: 31,
  },
  {
    id: "r5",
    productName: "Prismatic Evolutions Elite Trainer Box",
    retailer: "ebgames",
    location: "EB Games - Square One, Mississauga",
    postalCode: "L5B 2C9",
    status: "out_of_stock",
    note: "Went in 20 min after the last report and already gone. These fly.",
    reportedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    upvotes: 14,
  },
];
