import { Product, CommunityReport } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prismatic-evolutions-etb",
    name: "Prismatic Evolutions Elite Trainer Box",
    image: "/products/placeholder.png",
    category: "Elite Trainer Box",
    retailers: [
      {
        retailer: "target",
        url: "#",
        price: 54.99,
        status: "out_of_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: "2026-05-08T14:30:00Z",
      },
      {
        retailer: "walmart",
        url: "#",
        price: 54.99,
        status: "out_of_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: "2026-05-07T09:15:00Z",
      },
      {
        retailer: "pokemoncenter",
        url: "#",
        price: 54.99,
        status: "out_of_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: null,
      },
    ],
  },
  {
    id: "prismatic-evolutions-bbb",
    name: "Prismatic Evolutions Binder Collection",
    image: "/products/placeholder.png",
    category: "Collection Box",
    retailers: [
      {
        retailer: "target",
        url: "#",
        price: 39.99,
        status: "in_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: new Date().toISOString(),
      },
      {
        retailer: "gamestop",
        url: "#",
        price: 39.99,
        status: "out_of_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: "2026-05-09T11:00:00Z",
      },
    ],
  },
  {
    id: "surging-sparks-bb",
    name: "Surging Sparks Booster Box",
    image: "/products/placeholder.png",
    category: "Booster Box",
    retailers: [
      {
        retailer: "pokemoncenter",
        url: "#",
        price: 143.64,
        status: "in_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: new Date().toISOString(),
      },
      {
        retailer: "walmart",
        url: "#",
        price: 143.64,
        status: "out_of_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: "2026-05-06T16:45:00Z",
      },
      {
        retailer: "bestbuy",
        url: "#",
        price: 143.64,
        status: "preorder",
        lastChecked: new Date().toISOString(),
        lastInStock: null,
      },
    ],
  },
  {
    id: "destined-rivals-etb",
    name: "Destined Rivals Elite Trainer Box",
    image: "/products/placeholder.png",
    category: "Elite Trainer Box",
    retailers: [
      {
        retailer: "target",
        url: "#",
        price: 44.99,
        status: "in_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: new Date().toISOString(),
      },
      {
        retailer: "walmart",
        url: "#",
        price: 44.99,
        status: "in_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: new Date().toISOString(),
      },
      {
        retailer: "pokemoncenter",
        url: "#",
        price: 44.99,
        status: "out_of_stock",
        lastChecked: new Date().toISOString(),
        lastInStock: "2026-05-10T08:00:00Z",
      },
    ],
  },
  {
    id: "journey-together-bb",
    name: "Journey Together Booster Box",
    image: "/products/placeholder.png",
    category: "Booster Box",
    retailers: [
      {
        retailer: "pokemoncenter",
        url: "#",
        price: 143.64,
        status: "preorder",
        lastChecked: new Date().toISOString(),
        lastInStock: null,
      },
      {
        retailer: "gamestop",
        url: "#",
        price: 143.64,
        status: "preorder",
        lastChecked: new Date().toISOString(),
        lastInStock: null,
      },
    ],
  },
];

export const MOCK_REPORTS: CommunityReport[] = [
  {
    id: "r1",
    productName: "Prismatic Evolutions Elite Trainer Box",
    retailer: "target",
    location: "Target - Los Angeles, CA",
    zipCode: "90001",
    status: "in_stock",
    note: "Found 3 on the shelf near the front registers. Go quick!",
    reportedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    upvotes: 24,
  },
  {
    id: "r2",
    productName: "Prismatic Evolutions Binder Collection",
    retailer: "walmart",
    location: "Walmart Supercenter - Houston, TX",
    zipCode: "77001",
    status: "in_stock",
    note: "Vendor just restocked the card aisle. Plenty of Prismatic products.",
    reportedAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    upvotes: 18,
  },
  {
    id: "r3",
    productName: "Surging Sparks Booster Box",
    retailer: "gamestop",
    location: "GameStop - Chicago, IL",
    zipCode: "60601",
    status: "in_stock",
    note: "They have 5+ booster boxes behind the counter. Just ask.",
    reportedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    upvotes: 9,
  },
  {
    id: "r4",
    productName: "Destined Rivals Elite Trainer Box",
    retailer: "target",
    location: "Target - Brooklyn, NY",
    zipCode: "11201",
    status: "in_stock",
    note: "Full shelf reset. ETBs, tins, and blisters all in stock.",
    reportedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    upvotes: 31,
  },
];
